spring.application.name=checkout-payment-gateway

server.port=8090

bank.simulator.url=http://localhost:8080/payments
payment.allowed-currencies=GBP,USD,EUR

logging.level.com.checkout.payment=DEBUG

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
